name: YK-Boilerplate
options:
  bundleIdPrefix: com.yourcompany
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  defaultConfig: Debug

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"

configs:
  Debug: debug
  Release: release

packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire.git
    exactVersion: "5.10.2"
  VxHub:
    url: https://github.com/ersel95/VxHub-iOS.git
    branch: main

targets:
  YK-Boilerplate:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: YK-Boilerplate
        excludes:
          - "Core/BuildConfiguration/*.xcconfig"
    settings:
      base:
        INFOPLIST_FILE: YK-Boilerplate/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.boilerplate
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: false
      configs:
        Debug:
          PRODUCT_NAME: "Boilerplate Dev"
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          PRODUCT_NAME: "Boilerplate"
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: ""
    dependencies:
      - package: Alamofire
      - package: VxHub
